default_language_version:
  python: python3.8
repos:
  - repo: https://gitlab.com/pycqa/flake8
    rev: '3.7.9'  # pick a git hash / tag to point to
    hooks:
      - id: flake8
        args: [--exclude="./.*,./scripts/20*,vendor/*,node_modules/*" --max-line-length=88 --show-source, --statistics, "--select=E9,F63,F7,F82"]
