os: linux
dist: bionic
language: python
python: "3.8"
install:
  - pip install flake8
  - make lint
  - pip install -r requirements_test.txt
  # if Travis is running Python 3, then
  #   refresh the git submodule ./vendor/infogami
  #   create a legacy Python for npm/node until nodejs/node#25789 is resolved
  - if [ "$TRAVIS_PYTHON_VERSION" == "3.8" ]; then
      pushd vendor/infogami && git pull origin master && popd;
      pyenv install 2.7.14;
    fi
  - npm install
  - make i18n
jobs:
  include:
    - name: “Python 2.7 on bionic”
      python: "2.7"
      script: make test
    - script: pytest -v openlibrary/tests  # 28 failed, 135 passed
    - script: pytest -v openlibrary/plugins  # 6 failed, 78 passed
    - script: pytest -v openlibrary/catalog  # 39 failed, 138 passed
    - script: pytest -v openlibrary/coverstore  # 8 failed, 10 passed
    - script: pytest openlibrary/mocks openlibrary/olbase openlibrary/utils scripts/tests
