os: linux
dist: bionic
language: python
python: "3.8"
install:
  - pip install flake8
  - make lint
  - pip install -r requirements_test.txt
  # if Travis is running Python 3, then
  #   refresh the git submodule ./vendor/infogami
  #   create a legacy Python for npm/node until nodejs/node#25789 is resolved
  - if [ "$TRAVIS_PYTHON_VERSION" == "3.8" ]; then
      pushd vendor/infogami && git pull origin master && popd;
      pyenv install 2.7.14;
    fi
  - npm install
  - make i18n
jobs:
  include:
    - script: pytest openlibrary/tests  # 32 failed, 131 passed
    - script: pytest openlibrary/mocks
    - script: pytest openlibrary/olbase
    - script: pytest openlibrary/plugins  # 7 failed, 77 passed
    - script: pytest openlibrary/utils
    - script: pytest openlibrary/catalog  # 40 failed, 137 passed
    - script: pytest openlibrary/coverstore  # 7 failed, 11 passed
    - script: pytest scripts/tests
