name: lint_python
on: [pull_request, push]
jobs:
  lint_python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: sudo apt-get install libxml2-dev libxslt-dev
      - run: pip install --upgrade pip setuptools wheel
      - run: pip install -r requirements_test.txt
      - run: pushd vendor/infogami && git pull origin master && popd
      - run: pip list --outdated
      - run: make lint
      - run: make i18n
      - run: source scripts/run_doctests.sh
      - run: make test-py
